[input]
base_directory = "public"
url_prefix = "https://youpen-y.github.io/"
files = [
	{path = "posts/hello-world/index.html", url = "/posts/hello-world", title = "Hello World"},
	{path = "posts/test/index.html", url = "/posts/test", title = "测试"},
	{path = "posts/json/index.html", url = "/posts/json", title = "JSON 简介"},
	{path = "posts/immutable-sequences-concatenation/index.html", url = "/posts/immutable-sequences-concatenation", title = "Python Immutable Sequences Concatenation"},
	{path = "posts/ubuntu-template-trick/index.html", url = "/posts/ubuntu-template-trick", title = "The Ubuntu Templates Directory Hack"},
	{path = "posts/what-does-ai-mean/index.html", url = "/posts/what-does-ai-mean", title = "AI 意味着什么？"},
	{path = "posts/python-inspect/index.html", url = "/posts/python-inspect", title = "Python inspect 模块"},
	{path = "posts/tdd-with-claude-code/index.html", url = "/posts/tdd-with-claude-code", title = "TDD with Claude Code"},
	{path = "posts/claude-code-tools/index.html", url = "/posts/claude-code-tools", title = "Claude Code工具"},
]