[input]
base_directory = "public"
url_prefix = "https://youpen-y.github.io/"
files = [
	{path = "posts/hello-world/index.html", url = "/posts/hello-world", title = "Hello World"},
	{path = "posts/test/index.html", url = "/posts/test", title = "测试"},
	{path = "posts/json/index.html", url = "/posts/json", title = "JSON 简介"},
	{path = "posts/ubuntu-template-trick/index.html", url = "/posts/ubuntu-template-trick", title = "The Ubuntu Templates Directory Hack"}
]